name: Journal Publishing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 1,15 * *'

jobs:
  publish_journal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra qpdf

      - name: Convert all Markdown to PDF
        run: |
          mkdir -p journal_outputs
          for file in *.md; do
            pandoc "$file" -o "journal_outputs/${file%.md}.pdf"
          done
      
      - name: Convert all Markdown to HTML
        run: |
          for file in *.md; do
            pandoc "$file" -o "journal_outputs/${file%.md}.html"
          done

      - name: Convert all Markdown to EPUB
        run: |
          for file in *.md; do
            pandoc "$file" -o "journal_outputs/${file%.md}.epub"
          done

      - name: Merge PDFs into a single journal
        run: |
          qpdf --empty --pages journal_outputs/*.pdf -- snu_structural_review_final.pdf

      - name: Upload all journal formats
        uses: actions/upload-artifact@v4
        with:
          name: snu-structural-review-journal
          path: |
            snu_structural_review_final.pdf
            journal_outputs/*.html
            journal_outputs/*.epub
